name: augmented_reality_based_furniture_assistant_for_mandaue_foam_android
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # AR / 3D
  arcore_flutter_plugin: ^0.1.0
  model_viewer_plus: ^1.7.0
  url_launcher: ^6.3.0

  # Firebase
  firebase_core: ^4.1.0      # ⬅ bumped to match firebase_ai
  firebase_auth: ^6.0.2      # ⬅ bumped to match firebase_ai
  google_sign_in: ^6.2.1
  firebase_ai: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/models/
    - assets/thumbnails/
    - assets/google_logo.png
    - assets/Mandauefoam_Logo.png
