name: augmented_reality_based_furniture_assistant_for_mandaue_foam_android
description: A Flutter project with AR support
publish_to: "none"

environment:
  sdk: ">=3.5.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # ✅ AR plugin
dependency_overrides:
  ar_flutter_plugin:
    git:
      url: https://github.com/CariusLars/ar_flutter_plugin.git
      ref: main

  # ✅ Firebase
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  google_sign_in: ^6.3.0

  # ✅ AI & Utils
  google_generative_ai: ^0.4.0
  model_viewer_plus: ^1.9.3
  url_launcher: ^6.2.5
  vector_math: ^2.1.4
  shared_preferences: ^2.2.2

  # ✅ Device & Permissions
  geolocator: ^9.0.2
  device_info_plus: ^9.1.2
  permission_handler: ^10.4.5

  # ✅ Cupertino icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11

flutter:
  uses-material-design: true

  assets:
    - assets/google_logo.png
    - assets/mandauefoam_logo.png
    - assets/ar_models/
    - assets/ar_models/thumbnails/
