name: augmented_reality_based_furniture_assistant_for_mandaue_foam_android
description: A Flutter project with AR + Firebase + AI support
publish_to: "none"

environment:
  sdk: ">=3.5.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # ✅ Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.13.0
  firebase_storage: ^11.6.0

  # ✅ Google Sign-In
  google_sign_in: ^6.2.1

  # ✅ AR Plugin
  ar_flutter_plugin:
    git:
      url: https://github.com/CariusLars/ar_flutter_plugin.git
      ref: main

  # ✅ Generative AI
  google_generative_ai: ^0.4.0

  # ✅ Utils
  model_viewer_plus: ^1.9.3
  url_launcher: ^6.2.5
  vector_math: ^2.1.4
  shared_preferences: ^2.2.2
  geolocator: ^9.0.2
  device_info_plus: ^9.1.2
  permission_handler: ^10.4.5
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11

flutter:
  uses-material-design: true


  assets:
    # ✅ 3D Models
    - assets/models/Bradmor-4-Seater-Dining-Set.glb
    - assets/models/Coral-Desk1.glb
    - assets/models/Sofa-Random-Example.glb

    # ✅ JSON & Other Assets
    - assets/categories.json
    - assets/ar_models/
    - assets/furniture/
    - assets/google_logo.png
    - assets/mandauefoam_logo.png

    # ✅ Tutorial Images
    - assets/tutorial/page1.png
    - assets/tutorial/page2.png
    - assets/tutorial/page3.png
    - assets/tutorial/page4.png
