name: augmented_reality_based_furniture_assistant_for_mandaue_foam_android
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.15.2
  firebase_auth: ^5.1.1
  google_sign_in: ^6.2.1
  cupertino_icons: ^1.0.8
  arcore_flutter_plugin: ^0.1.0
  url_launcher: ^6.3.1
  firebase_ai: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/models/
    - assets/thumbnails/