name: augmented_reality_based_furniture_assistant_for_mandaue_foam_android
description: A Flutter project with AR support

publish_to: "none"

environment:
  sdk: '>=3.5.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase + Google Sign In
  firebase_core: ^2.32.0
  firebase_auth: ^4.16.3
  google_sign_in: ^6.1.5

  # AR
  ar_flutter_plugin: ^0.7.3

  # 3D Model Viewer
  model_viewer_plus: ^1.7.0

  # Google Gemini AI
  google_generative_ai: ^0.4.6

  # Other utilities
  url_launcher: ^6.2.5
  cupertino_icons: ^1.0.8
  vector_math: ^2.1.4
  flutter_lints: ^3.0.1

