// main.dart
import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:ar_flutter_plugin/ar_flutter_plugin.dart';

// Local imports
import 'auth_service.dart';
import 'firebase_options.dart'; // generated by flutterfire CLI
import 'ai_assistant_screen.dart';
import 'customer_home_screen.dart';
import 'login_screen.dart';
import 'signup_screen.dart';


void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'AR Furniture Assistant',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      initialRoute: '/',
      routes: {
        '/': (context) => const LoginScreen(),
        '/signup': (context) => const SignUpScreen(),   // fixed
        '/customer_home': (context) => const CustomerHomeScreen(),
        '/ai_assistant': (context) => const AiAssistantScreen(),
      },
    );
  }
}
