import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';


// ✅ Import your firebase options (generated by FlutterFire CLI)
import 'firebase_options.dart';
import 'services/firebase_options.dart';

// ✅ Import your screens
import 'screens/customer_home_screen.dart';
import 'screens/ar_view_screen.dart';
import 'login_screen.dart';


void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // ✅ Initialize Firebase
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      initialRoute: '/login',
      routes: {
        '/login': (context) => LoginScreen(),
        '/home': (context) => CustomerHomeScreen(),
      },
    );
  }
}